name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    env:
      PIP_DISABLE_PIP_VERSION_CHECK: on

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    #----------------------------------------------
    #           Get changed python files
    #----------------------------------------------
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v14.3
      with:
        files: |
          backend/**/*.py
          !backend/**/migrations/*.py
    #----------------------------------------------
    #             Print modified files
    #----------------------------------------------
    - name: List all modified files
      run: |
        for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
          echo "$file was modified"
        done
    #----------------------------------------------
    #        Run Pylint on each changed file
    #----------------------------------------------
    - name: Run pylint
      run: |
        for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            pylint --exit-zero --rcfile=pylintrc $file
        done
